### PR TITLE
Added the missing client secret parameter in appsettings

### PR DESCRIPTION
**Pull request by ProgrammingWithDJ**
- Added Missing client secret key in appsettings.Json file.
- Removed the hardcoded value to Parameterized the AppAuth type to take values of Scopes from Appsettings.

### CODE REVIEW

**Comment by jasonjoh** [comment]
Thanks for this @ProgrammingWithDJ! The reason I did not read scopes from the settings JSON is because with app-only auth (client_credentials flow) you always have to use the `https://graph.microsoft.com/.default` value. Having it be configurable doesn't make sense.

**Comment by ProgrammingWithDJ** [comment]
@jasonjoh Yes that makes sense, I thought of making the code more readable.

Do you want me to remove the files and the client secret attribute from app settings? Please let me know.

**Comment by jasonjoh** [comment]
Yes. Putting `clientSecret` into appsettings.json will work, but it's better to put it in the secret manager on the local box.

**Comment by jasonjoh** [comment]
Closing PR

**Pull request closed without merging**
